description: Daniel Nguyen - Designer Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://daniel-nguyen.net" # the base hostname & protocol for your site, e.g., http://yourwebsite.com

# User settings
username: Daniel Nguyen
user_description: I'm a designer passionate about creating meaningful and innovative designs. Always eager to explore new ideas and push the boundaries of creativity.
user_title: Designer
email: "mailto:contact@danielnguyen.onmail.com"
youtube_username: daniel-nguyen
github_username: dansc89

exclude: ['package.json', 'src', 'node_modules', 'vendor']
